/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and sends an email confirmation link.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Confirm email address
         * @description Validates the confirmation token and marks the user's email as confirmed.
         */
        get: operations["AuthController_confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend confirmation email
         * @description Resends the email confirmation link. No-op if the email is already confirmed or does not exist.
         */
        post: operations["AuthController_resendConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticates a confirmed user and returns an access + refresh token pair.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Issues a new access + refresh token pair using a valid refresh token.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request password reset
         * @description Sends a password reset email. No-op if the email is not registered.
         */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password
         * @description Resets the user password using a valid reset token.
         */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revokes all active refresh tokens for the authenticated user.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the authenticated user's profile from the JWT payload.
         */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a video upload
         * @description Pre-registers the video as a draft in the caller channel and opens an S3 multipart upload. The client then uploads each part directly to the object storage using presigned URLs — the file never passes through the API.
         */
        post: operations["VideosController_initiateUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/upload/part-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sign part upload URLs
         * @description Returns presigned UploadPart URLs (up to 100 per call). The client PUTs each part to its URL and keeps the returned ETag.
         */
        get: operations["VideosController_signPartUrls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/upload/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a video upload
         * @description Completes the multipart upload, checks the real object size and enqueues the background processing (duration, metadata, thumbnail).
         */
        post: operations["VideosController_completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Abort a video upload
         * @description Aborts the multipart upload in progress and removes the draft video.
         */
        delete: operations["VideosController_abortUpload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{slug}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a video
         * @description Redirects to a presigned GET of the original on the object storage, which answers `Range` requests with `206 Partial Content` — players seek without downloading the whole file.
         */
        get: operations["VideosController_streamVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{slug}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a video
         * @description Redirects to a presigned GET of the original served as `Content-Disposition: attachment` with the original file name.
         */
        get: operations["VideosController_downloadVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{slug}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a video thumbnail
         * @description Redirects to a presigned GET of the JPEG thumbnail generated by the video worker.
         */
        get: operations["VideosController_getThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an owned video
         * @description Returns the upload/processing status and the extracted metadata of a video owned by the caller.
         */
        get: operations["VideosController_getOwnedVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        ResendConfirmationDto: {
            /** Format: email */
            email: string;
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshTokenDto: {
            refresh_token: string;
        };
        ForgotPasswordDto: {
            /** Format: email */
            email: string;
        };
        ResetPasswordDto: {
            token: string;
            new_password: string;
        };
        CreateVideoDto: {
            file_name: string;
            /** @description Declared size in bytes; values above 10 GiB are rejected with VIDEO_TOO_LARGE. */
            size_bytes: number;
            /** @description One of video/mp4, video/webm, video/quicktime, video/x-matroska. */
            content_type: string;
            /** @description Defaults to the file name without extension. */
            title?: string;
        };
        /** @enum {string} */
        VideoStatus: "draft" | "processing" | "ready" | "failed";
        InitiatedUploadResponseDto: {
            /**
             * Format: uuid
             * @example 5b0c8a4e-6f7d-4a53-9b1e-2f4f0d6a9c11
             */
            id: string;
            /**
             * @description Unique URL identifier (11-char base62)
             * @example aZ3kP9xQ2mB
             */
            slug: string;
            /** @example minha-viagem */
            title: string;
            /** @example draft */
            status: components["schemas"]["VideoStatus"];
            /**
             * @description Every part but the last has exactly this size
             * @example 67108864
             */
            part_size_bytes: number;
            /** @example 3 */
            part_count: number;
        };
        SignedPartUrlDto: {
            /** @example 1 */
            part_number: number;
            /**
             * Format: uri
             * @description Presigned UploadPart URL — PUT the part bytes and keep the ETag
             */
            url: string;
        };
        PartUrlsResponseDto: {
            parts: components["schemas"]["SignedPartUrlDto"][];
            /** @example 3600 */
            expires_in_seconds: number;
        };
        UploadedPartDto: {
            part_number: number;
            /** @description ETag returned by the storage for the part's PUT. */
            etag: string;
        };
        CompleteUploadDto: {
            parts: components["schemas"]["UploadedPartDto"][];
        };
        CompletedUploadResponseDto: {
            /**
             * Format: uuid
             * @example 5b0c8a4e-6f7d-4a53-9b1e-2f4f0d6a9c11
             */
            id: string;
            /** @example aZ3kP9xQ2mB */
            slug: string;
            /** @example minha-viagem */
            title: string;
            /** @example processing */
            status: components["schemas"]["VideoStatus"];
        };
        VideoMetadataDto: {
            /** @example mov,mp4,m4a,3gp,3g2,mj2 */
            container: string | null;
            /** @example h264 */
            video_codec: string | null;
            /** @example aac */
            audio_codec: string | null;
            /** @example 1920 */
            width: number | null;
            /** @example 1080 */
            height: number | null;
            /** @example 29.97 */
            fps: number | null;
            /**
             * @description Bits per second
             * @example 4500000
             */
            bitrate: number | null;
        };
        VideoDetailsResponseDto: {
            /**
             * Format: uuid
             * @example 5b0c8a4e-6f7d-4a53-9b1e-2f4f0d6a9c11
             */
            id: string;
            /** @example aZ3kP9xQ2mB */
            slug: string;
            /** @example minha-viagem */
            title: string;
            /** @example ready */
            status: components["schemas"]["VideoStatus"];
            /** @example minha-viagem.mp4 */
            original_file_name: string;
            /** @example video/mp4 */
            content_type: string;
            /** @example 137282022 */
            size_bytes: number;
            /**
             * @description Set by the worker once the video is ready
             * @example 60
             */
            duration_seconds: number | null;
            metadata: components["schemas"]["VideoMetadataDto"] | null;
            /** @description Whether GET /videos/:slug/thumbnail can serve an image */
            has_thumbnail: boolean;
            /**
             * @description Failure reason when status is failed
             * @example null
             */
            processing_error: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ApiErrorEnvelope: {
            /** @example 401 */
            statusCode: number;
            /** @example INVALID_CREDENTIALS */
            error: string;
            /** @example Invalid email or password */
            message: string | string[];
            code?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email confirmed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid or expired confirmation token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_resendConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendConfirmationDto"];
            };
        };
        responses: {
            /** @description Confirmation email sent (or silently skipped if already confirmed) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        refresh_token?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Email not confirmed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        refresh_token?: string;
                    };
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid, expired, or reused refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Reset email sent (or silently skipped if email not found) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Invalid or expired reset token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sub?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_initiateUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVideoDto"];
            };
        };
        responses: {
            /** @description Draft created with its upload plan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiatedUploadResponseDto"];
                };
            };
            /** @description VALIDATION_ERROR, UNSUPPORTED_VIDEO_FORMAT (mp4, webm, mov, mkv only) or VIDEO_TOO_LARGE (> 10 GiB) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VideosController_signPartUrls: {
        parameters: {
            query: {
                /** @description Comma-separated part numbers, e.g. `1,2,3` (max 100 per request). */
                part_numbers: number[];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned part URLs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartUrlsResponseDto"];
                };
            };
            /** @description VALIDATION_ERROR or INVALID_PART_NUMBER */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description VIDEO_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description INVALID_VIDEO_STATE — the video is not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadDto"];
            };
        };
        responses: {
            /** @description Upload completed; processing enqueued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedUploadResponseDto"];
                };
            };
            /** @description VALIDATION_ERROR, INVALID_UPLOAD_PARTS or UPLOAD_SIZE_MISMATCH (video marked failed) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description VIDEO_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description INVALID_VIDEO_STATE — the video is not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_abortUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload aborted, draft removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description VIDEO_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description INVALID_VIDEO_STATE — the video is not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
    VideosController_streamVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the streamable original */
            302: {
                headers: {
                    /** @description Presigned object storage URL, valid for S3_PRESIGN_EXPIRES_SECONDS */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_NOT_FOUND — unknown slug or the video is not ready (draft, processing or failed) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Too many playback requests (120 per minute) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VideosController_downloadVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the original as an attachment */
            302: {
                headers: {
                    /** @description Presigned object storage URL, valid for S3_PRESIGN_EXPIRES_SECONDS */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_NOT_FOUND — unknown slug or the video is not ready (draft, processing or failed) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Too many playback requests (120 per minute) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VideosController_getThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the JPEG thumbnail */
            302: {
                headers: {
                    /** @description Presigned object storage URL, valid for S3_PRESIGN_EXPIRES_SECONDS */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_NOT_FOUND — unknown slug or the video is not ready (draft, processing or failed) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Too many playback requests (120 per minute) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VideosController_getOwnedVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Video details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetailsResponseDto"];
                };
            };
            /** @description VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VIDEO_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
            /** @description VIDEO_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorEnvelope"];
                };
            };
        };
    };
}
